language: java
jdk: openjdk15
node_js:
  - '12'
# Handle git submodules yourself
git:
  submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
- sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
- git submodule update --init --recursive
- nvm install node
- npm install
- npm install -g grunt-cli
script:
- ./gradlew build -x ktlint
- ./gradlew ktlint
- grunt test
after_success:
- ./gradlew dokka
- git clone -b gh-pages https://github.com/ThaumicMekanism/venus.git out && rm -rf out/.git
- test $TRAVIS_BRANCH = "js" && mv out/jvm jvm && rm -rf out && mkdir out && mv jvm out && grunt dist && mv docs out
- test $TRAVIS_BRANCH = "jvm" && rm -rf out/jvm && grunt distjvm && mv docs out/jvm
cache:
  directories:
  - node_modules/
deploy:
- provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: out
  keep-history: true
  on:
    branch: js
  email: deployer@travis-ci.org
  name: Travis CI Deployment

- provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: out
  keep-history: true
  on:
    branch: jvm
  email: deployer@travis-ci.org
  name: Travis CI Deployment

#  - provider: releases
#  github_token: $GITHUB_TOKEN
#  file_glob: true
#  file: build/libs/venus-*.jar
#  skip_cleanup: true
#  email: deployer@travis-ci.org
#  name: Travis CI Deployment
#  on:
#    tags: true
#    branch: